# Docker file for rabbitmq single or cluster from bolingcavalry 
# VERSION 0.0.1
# Author: skyrim
# Time: 2024/3/7


# 使用官方的 RabbitMQ 镜像作为基础镜像
FROM rabbitmq:3.8

# 设置环境变量
ENV RABBITMQ_DEFAULT_USER=admin
ENV RABBITMQ_DEFAULT_PASS=password

# 暴露 RabbitMQ 默认端口
EXPOSE 5672 15672
